name: Deploy DAGs via GitActions

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy EC2 via GitActions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SAMRA_AIRFLOW_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          
          script: |
            cd /home/ubuntu/samra-airflow
            git fetch
            git pull
